name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: nuget restore
      
    - name: Set Android version
      uses: damienaicheh/update-android-version-manifest-action@v1.0.0
      with:
        android-manifest-path: ./CoralClient/CoralClient.Android/Properties/AndroidManifest.xml
        version-name: ${{ secrets.APP_VERSION }}
        version-code: ${{ github.run_number }}
        
    - name: Build
      run: msbuild ./CoralClient/CoralClient.Android/CoralClient.Android.csproj /t:PackageForAndroid /t:SignAndroidPackage /p:Configuration=Release
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        path: "**/bin/Release/*.apk"
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1      
      with:
        tag_name: ${{ github.workflow }}
        name: CoralClient v${{ secrets.APP_VERSION }} (Build ${{ github.run_number }})
        draft: false
        prerelease: false
        files: "**/bin/Release/*.apk"
