name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Set Android version
      uses: damienaicheh/update-android-version-manifest-action@v1.0.0
      with:
        android-manifest-path: ./CoralClient/CoralClient.Android/Properties/AndroidManifest.xml
        version-name: ${{ secrets.APP_VERSION }}
        version-code: ${{ github.run_number }}
        
    - name: Build Android
      run: MSBuild /p:Configuration=Release /p:AndroidPackageFormat=apk ./CoralClient/CoralClient.Android/CoralClient.Android.csproj
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        path: "**/*.apk"
